//go:build linux

package macosnetwork

import (
	"context"
	"errors"
	"reflect"
	"strings"
	"testing"

	"open-mihomo-gateway/internal/runtime"
)

func TestParseIPAddr(t *testing.T) {
	const eth0 = `[{"ifindex":2,"ifname":"eth0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],` +
		`"link_type":"ether","address":"aa:bb:cc:dd:ee:ff","addr_info":[` +
		`{"family":"inet6","local":"fe80::1","prefixlen":64,"scope":"link"},` +
		`{"family":"inet","local":"192.168.1.20","prefixlen":24,"scope":"global","label":"eth0"}]}]`

	tests := []struct {
		name       string
		output     string
		iface      string
		wantIPv4   string
		wantMask   string
		wantMAC    string
		wantErrLog string
	}{
		{name: "ipv4 and mac", output: eth0, iface: "eth0", wantIPv4: "192.168.1.20", wantMask: "255.255.255.0", wantMAC: "aa:bb:cc:dd:ee:ff"},
		{
			name:     "no ipv4 keeps mac",
			output:   `[{"ifname":"eth1","address":"11:22:33:44:55:66","addr_info":[{"family":"inet6","local":"fe80::2","prefixlen":64}]}]`,
			iface:    "eth1",
			wantIPv4: "", wantMask: "", wantMAC: "11:22:33:44:55:66",
		},
		{name: "prefix 16", output: `[{"ifname":"eth0","address":"aa:bb:cc:dd:ee:ff","addr_info":[{"family":"inet","local":"10.0.0.5","prefixlen":16}]}]`, iface: "eth0", wantIPv4: "10.0.0.5", wantMask: "255.255.0.0", wantMAC: "aa:bb:cc:dd:ee:ff"},
		{name: "unknown interface", output: eth0, iface: "eth9", wantErrLog: "was not found"},
		{name: "not json", output: "eth0: <BROADCAST>", iface: "eth0", wantErrLog: "parse ip addr output"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseIPAddr(tc.output, tc.iface)
			if tc.wantErrLog != "" {
				if err == nil || !strings.Contains(err.Error(), tc.wantErrLog) {
					t.Fatalf("err = %v, want containing %q", err, tc.wantErrLog)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if got.IPv4 != tc.wantIPv4 || got.SubnetMask != tc.wantMask || got.HardwareAddr != tc.wantMAC {
				t.Fatalf("parseIPAddr() = %#v", got)
			}
			if got.DNS == nil {
				t.Fatal("DNS must be an empty slice, not nil (JSON contract)")
			}
		})
	}
}

func TestDefaultGateway(t *testing.T) {
	const routes = `[{"dst":"default","gateway":"192.168.1.1","dev":"eth0","protocol":"dhcp","metric":100},` +
		`{"dst":"default","gateway":"10.0.0.1","dev":"eth1","metric":200}]`

	tests := []struct {
		name   string
		output string
		iface  string
		want   string
	}{
		{name: "first interface", output: routes, iface: "eth0", want: "192.168.1.1"},
		{name: "second interface", output: routes, iface: "eth1", want: "10.0.0.1"},
		{name: "no route on interface", output: routes, iface: "eth2", want: ""},
		{name: "empty list", output: `[]`, iface: "eth0", want: ""},
		{name: "gatewayless route", output: `[{"dst":"default","dev":"tun0"}]`, iface: "tun0", want: ""},
		{name: "not json", output: "default via 192.168.1.1 dev eth0", iface: "eth0", want: ""},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := defaultGateway(tc.output, tc.iface); got != tc.want {
				t.Fatalf("defaultGateway() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestHasDefaultRouteDev(t *testing.T) {
	// IPv6 默认路由常常没有 gateway 字段（on-link），所以只看 dev。
	const routes6 = `[{"dst":"default","dev":"eth0","protocol":"ra","metric":1024}]`
	if !hasDefaultRouteDev(routes6, "eth0") {
		t.Fatal("IPv6 default route not detected")
	}
	if hasDefaultRouteDev(routes6, "eth1") {
		t.Fatal("IPv6 default route detected on wrong interface")
	}
}

func TestParseResolvConf(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    []string
	}{
		{
			name:    "typical fnos resolv.conf",
			content: "# Generated by NetworkManager\nsearch lan\nnameserver 192.168.1.1\nnameserver 1.1.1.1\n",
			want:    []string{"192.168.1.1", "1.1.1.1"},
		},
		{name: "commented out", content: "#nameserver 8.8.8.8\n", want: []string{}},
		{name: "ipv6 nameserver", content: "nameserver fe80::1\n", want: []string{"fe80::1"}},
		{name: "garbage value", content: "nameserver not-an-ip\n", want: []string{}},
		{name: "empty", content: "", want: []string{}},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseResolvConf(tc.content); !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("parseResolvConf() = %#v, want %#v", got, tc.want)
			}
		})
	}
}

func TestParseRouteGet(t *testing.T) {
	tests := []struct {
		name        string
		output      string
		wantIface   string
		wantGateway string
	}{
		{
			name:        "via gateway",
			output:      `[{"dst":"1.1.1.1","gateway":"198.18.0.1","dev":"utun42","prefsrc":"198.18.0.2","flags":[],"uid":0,"cache":[]}]`,
			wantIface:   "utun42",
			wantGateway: "198.18.0.1",
		},
		{name: "on-link", output: `[{"dst":"192.168.1.1","dev":"eth0","prefsrc":"192.168.1.20","flags":[]}]`, wantIface: "eth0"},
		{name: "empty", output: `[]`},
		{name: "not json", output: "1.1.1.1 via 198.18.0.1 dev utun42"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := parseRouteGet(tc.output)
			if got.Interface != tc.wantIface || got.Gateway != tc.wantGateway {
				t.Fatalf("parseRouteGet() = %#v", got)
			}
		})
	}
}

func TestLookupRouteReturnsSelectedInterface(t *testing.T) {
	original := runCommand
	t.Cleanup(func() { runCommand = original })
	runCommand = func(_ context.Context, binary string, args ...string) (string, error) {
		if binary != "ip" || strings.Join(args, " ") != "-j route get 1.0.0.0" {
			t.Fatalf("command = %s %#v", binary, args)
		}
		return `[{"dst":"1.0.0.0","gateway":"198.18.0.1","dev":"utun42"}]`, nil
	}

	route, err := LookupRoute(t.Context(), "1.0.0.0")
	if err != nil {
		t.Fatal(err)
	}
	if route.Interface != "utun42" || route.Gateway != "198.18.0.1" {
		t.Fatalf("route = %#v", route)
	}
}

func TestHostNetworkWritesAreRefused(t *testing.T) {
	ctx := t.Context()
	cfg := ManualConfig{NetworkService: "eth0", Interface: "eth0", IPv4: "192.168.1.20", SubnetMask: "255.255.255.0", Router: "192.168.1.1"}
	var snapshot runtime.SystemProxySnapshot

	serviceInterface := func() error { _, err := ServiceInterface(ctx, "eth0"); return err }
	probeDHCP := func() error { _, err := ProbeDHCPServers(ctx, "eth0", 0); return err }
	prepareProxy := func() error { _, err := SystemProxy{}.Prepare(ctx, "eth0", 7890); return err }

	tests := map[string]func() error{
		"SetManual":           func() error { return SetManual(ctx, cfg) },
		"SetDHCP":             func() error { return SetDHCP(ctx, "eth0") },
		"ServiceInterface":    serviceInterface,
		"ProbeDHCPServers":    probeDHCP,
		"SystemProxy.Prepare": prepareProxy,
		"SystemProxy.Enable":  func() error { return SystemProxy{}.Enable(ctx, snapshot, 7890) },
		"SystemProxy.Restore": func() error { return SystemProxy{}.Restore(ctx, snapshot) },
	}

	for name, call := range tests {
		t.Run(name, func(t *testing.T) {
			if err := call(); !errors.Is(err, ErrManagedByFnOS) {
				t.Fatalf("error = %v, want ErrManagedByFnOS", err)
			}
		})
	}
}
